server:
  context-path: /client2
  port: 8082



security:
  oauth2:
    client:
      client-id: client2
      client-secret: client2
      user-authorization-uri: http://localhost:8090/server/oauth/authorize
      access-token-uri: http://localhost:8090/server/oauth/token
      authentication-scheme: form
    authorization:
      check-token-access: http://localhost:8090/server/oauth/check_token
    sso:
      login-path: /login
    resource:
      user-info-uri: http://localhost:8090/server/oauth/user
      token-info-uri: http://localhost:8090/server/oauth/resource_token
      prefer-token-info: false


logging:
  level:
    com:
      boxfish: info
    org:
      springframework: debug