server:
  context-path: /client1
  port: 8081

security:
  oauth2:
    client:
      client-id: client1
      client-secret: 123456
      user-authorization-uri: http://localhost:8090/server/oauth/authorize
      access-token-uri: http://localhost:8090/server/oauth/token
      authentication-scheme: form
    authorization:
      check-token-access: http://localhost:8090/server/oauth/check_token
#      token-key-access: http://localhost:8090/server/oauth/token_key
    resource:
#      user-info-uri: http://localhost:8090/server/oauth/user
      jwt:
#        key-value: |
#          -----BEGIN PUBLIC KEY-----
#              MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDNQZKqTlO/+2b4ZdhqGJzGBDlt
#              b5PZmBz1ALN2YLvt341pH6i5mO1V9cX5Ty1LM70fKfnIoYUP4KCE33dPnC7LkUwE
#              /myh1zM6m8cbL5cYFPyP099thbVxzJkjHWqywvQih/qOOjliomKbM9pxG8Z1dB26
#              hL9dSAZuA8xExjlPmQIDAQAB
#          -----END PUBLIC KEY-----
        key-uri: http://localhost:8090/server/oauth/token_key




logging:
  level:
    demo: info
    org:
      springframework: info

#debug: true